'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace WcfKatahikiRenkei
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpBinding_IKatahikiRenkeiService", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class KatahikiRenkeiService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetStandardNokiOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetElKubunOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetElFlagOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetQuantityUnitOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetNetPriceOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetSwitchFlgOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetSelectCatalogOperationCompleted As System.Threading.SendOrPostCallback
        
        Private IsGlcOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetMItemByLanguageOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WebKataban.My.MySettings.Default.WebKataban_WcfKatahikiRenkei_KatahikiRenkeiService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetStandardNokiCompleted As GetStandardNokiCompletedEventHandler
        
        '''<remarks/>
        Public Event GetElKubunCompleted As GetElKubunCompletedEventHandler
        
        '''<remarks/>
        Public Event GetElFlagCompleted As GetElFlagCompletedEventHandler
        
        '''<remarks/>
        Public Event GetQuantityUnitCompleted As GetQuantityUnitCompletedEventHandler
        
        '''<remarks/>
        Public Event GetNetPriceCompleted As GetNetPriceCompletedEventHandler
        
        '''<remarks/>
        Public Event GetSwitchFlgCompleted As GetSwitchFlgCompletedEventHandler
        
        '''<remarks/>
        Public Event GetSelectCatalogCompleted As GetSelectCatalogCompletedEventHandler
        
        '''<remarks/>
        Public Event IsGlcCompleted As IsGlcCompletedEventHandler
        
        '''<remarks/>
        Public Event GetMItemByLanguageCompleted As GetMItemByLanguageCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IKatahikiRenkeiService/GetStandardNoki", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetStandardNoki(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal strKata As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal strPlaceId As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> StandardNouki
            Dim results() As Object = Me.Invoke("GetStandardNoki", New Object() {strKata, strPlaceId})
            Return CType(results(0),StandardNouki)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetStandardNokiAsync(ByVal strKata As String, ByVal strPlaceId As String)
            Me.GetStandardNokiAsync(strKata, strPlaceId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetStandardNokiAsync(ByVal strKata As String, ByVal strPlaceId As String, ByVal userState As Object)
            If (Me.GetStandardNokiOperationCompleted Is Nothing) Then
                Me.GetStandardNokiOperationCompleted = AddressOf Me.OnGetStandardNokiOperationCompleted
            End If
            Me.InvokeAsync("GetStandardNoki", New Object() {strKata, strPlaceId}, Me.GetStandardNokiOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetStandardNokiOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetStandardNokiCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetStandardNokiCompleted(Me, New GetStandardNokiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IKatahikiRenkeiService/GetElKubun", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub GetElKubun(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal strKataban As String, ByRef GetElKubunResult As Boolean, <System.Xml.Serialization.XmlIgnoreAttribute()> ByRef GetElKubunResultSpecified As Boolean)
            Dim results() As Object = Me.Invoke("GetElKubun", New Object() {strKataban})
            GetElKubunResult = CType(results(0),Boolean)
            GetElKubunResultSpecified = CType(results(1),Boolean)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetElKubunAsync(ByVal strKataban As String)
            Me.GetElKubunAsync(strKataban, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetElKubunAsync(ByVal strKataban As String, ByVal userState As Object)
            If (Me.GetElKubunOperationCompleted Is Nothing) Then
                Me.GetElKubunOperationCompleted = AddressOf Me.OnGetElKubunOperationCompleted
            End If
            Me.InvokeAsync("GetElKubun", New Object() {strKataban}, Me.GetElKubunOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetElKubunOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetElKubunCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetElKubunCompleted(Me, New GetElKubunCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IKatahikiRenkeiService/GetElFlag", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetElFlag(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal strKataban As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("GetElFlag", New Object() {strKataban})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetElFlagAsync(ByVal strKataban As String)
            Me.GetElFlagAsync(strKataban, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetElFlagAsync(ByVal strKataban As String, ByVal userState As Object)
            If (Me.GetElFlagOperationCompleted Is Nothing) Then
                Me.GetElFlagOperationCompleted = AddressOf Me.OnGetElFlagOperationCompleted
            End If
            Me.InvokeAsync("GetElFlag", New Object() {strKataban}, Me.GetElFlagOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetElFlagOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetElFlagCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetElFlagCompleted(Me, New GetElFlagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IKatahikiRenkeiService/GetQuantityUnit", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetQuantityUnit(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal strKataban As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal strLanguage As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal strLanguageDefault As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> QuantityUnit
            Dim results() As Object = Me.Invoke("GetQuantityUnit", New Object() {strKataban, strLanguage, strLanguageDefault})
            Return CType(results(0),QuantityUnit)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetQuantityUnitAsync(ByVal strKataban As String, ByVal strLanguage As String, ByVal strLanguageDefault As String)
            Me.GetQuantityUnitAsync(strKataban, strLanguage, strLanguageDefault, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetQuantityUnitAsync(ByVal strKataban As String, ByVal strLanguage As String, ByVal strLanguageDefault As String, ByVal userState As Object)
            If (Me.GetQuantityUnitOperationCompleted Is Nothing) Then
                Me.GetQuantityUnitOperationCompleted = AddressOf Me.OnGetQuantityUnitOperationCompleted
            End If
            Me.InvokeAsync("GetQuantityUnit", New Object() {strKataban, strLanguage, strLanguageDefault}, Me.GetQuantityUnitOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetQuantityUnitOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetQuantityUnitCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetQuantityUnitCompleted(Me, New GetQuantityUnitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IKatahikiRenkeiService/GetNetPrice", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetNetPrice(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal strKataban As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal strImportCountryCode As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal strExportCountryCode As String, ByVal decGsPrice As Decimal, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal decGsPriceSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal strBaseCurrency As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("GetNetPrice", New Object() {strKataban, strImportCountryCode, strExportCountryCode, decGsPrice, decGsPriceSpecified, strBaseCurrency})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetNetPriceAsync(ByVal strKataban As String, ByVal strImportCountryCode As String, ByVal strExportCountryCode As String, ByVal decGsPrice As Decimal, ByVal decGsPriceSpecified As Boolean, ByVal strBaseCurrency As String)
            Me.GetNetPriceAsync(strKataban, strImportCountryCode, strExportCountryCode, decGsPrice, decGsPriceSpecified, strBaseCurrency, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetNetPriceAsync(ByVal strKataban As String, ByVal strImportCountryCode As String, ByVal strExportCountryCode As String, ByVal decGsPrice As Decimal, ByVal decGsPriceSpecified As Boolean, ByVal strBaseCurrency As String, ByVal userState As Object)
            If (Me.GetNetPriceOperationCompleted Is Nothing) Then
                Me.GetNetPriceOperationCompleted = AddressOf Me.OnGetNetPriceOperationCompleted
            End If
            Me.InvokeAsync("GetNetPrice", New Object() {strKataban, strImportCountryCode, strExportCountryCode, decGsPrice, decGsPriceSpecified, strBaseCurrency}, Me.GetNetPriceOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetNetPriceOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetNetPriceCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetNetPriceCompleted(Me, New GetNetPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IKatahikiRenkeiService/GetSwitchFlg", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub GetSwitchFlg(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal strKataban As String, ByRef GetSwitchFlgResult As Boolean, <System.Xml.Serialization.XmlIgnoreAttribute()> ByRef GetSwitchFlgResultSpecified As Boolean)
            Dim results() As Object = Me.Invoke("GetSwitchFlg", New Object() {strKataban})
            GetSwitchFlgResult = CType(results(0),Boolean)
            GetSwitchFlgResultSpecified = CType(results(1),Boolean)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSwitchFlgAsync(ByVal strKataban As String)
            Me.GetSwitchFlgAsync(strKataban, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSwitchFlgAsync(ByVal strKataban As String, ByVal userState As Object)
            If (Me.GetSwitchFlgOperationCompleted Is Nothing) Then
                Me.GetSwitchFlgOperationCompleted = AddressOf Me.OnGetSwitchFlgOperationCompleted
            End If
            Me.InvokeAsync("GetSwitchFlg", New Object() {strKataban}, Me.GetSwitchFlgOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetSwitchFlgOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSwitchFlgCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSwitchFlgCompleted(Me, New GetSwitchFlgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IKatahikiRenkeiService/GetSelectCatalog", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSelectCatalog(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal strKataban As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> SelectCatalog
            Dim results() As Object = Me.Invoke("GetSelectCatalog", New Object() {strKataban})
            Return CType(results(0),SelectCatalog)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetSelectCatalogAsync(ByVal strKataban As String)
            Me.GetSelectCatalogAsync(strKataban, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSelectCatalogAsync(ByVal strKataban As String, ByVal userState As Object)
            If (Me.GetSelectCatalogOperationCompleted Is Nothing) Then
                Me.GetSelectCatalogOperationCompleted = AddressOf Me.OnGetSelectCatalogOperationCompleted
            End If
            Me.InvokeAsync("GetSelectCatalog", New Object() {strKataban}, Me.GetSelectCatalogOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetSelectCatalogOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSelectCatalogCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSelectCatalogCompleted(Me, New GetSelectCatalogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IKatahikiRenkeiService/IsGlc", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub IsGlc(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal strKataban As String, ByRef IsGlcResult As Boolean, <System.Xml.Serialization.XmlIgnoreAttribute()> ByRef IsGlcResultSpecified As Boolean)
            Dim results() As Object = Me.Invoke("IsGlc", New Object() {strKataban})
            IsGlcResult = CType(results(0),Boolean)
            IsGlcResultSpecified = CType(results(1),Boolean)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub IsGlcAsync(ByVal strKataban As String)
            Me.IsGlcAsync(strKataban, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub IsGlcAsync(ByVal strKataban As String, ByVal userState As Object)
            If (Me.IsGlcOperationCompleted Is Nothing) Then
                Me.IsGlcOperationCompleted = AddressOf Me.OnIsGlcOperationCompleted
            End If
            Me.InvokeAsync("IsGlc", New Object() {strKataban}, Me.IsGlcOperationCompleted, userState)
        End Sub
        
        Private Sub OnIsGlcOperationCompleted(ByVal arg As Object)
            If (Not (Me.IsGlcCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent IsGlcCompleted(Me, New IsGlcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IKatahikiRenkeiService/GetMItemByLanguage", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMItemByLanguage(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal strLanguage As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal strKisyuCode As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> MItem
            Dim results() As Object = Me.Invoke("GetMItemByLanguage", New Object() {strLanguage, strKisyuCode})
            Return CType(results(0),MItem)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetMItemByLanguageAsync(ByVal strLanguage As String, ByVal strKisyuCode As String)
            Me.GetMItemByLanguageAsync(strLanguage, strKisyuCode, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetMItemByLanguageAsync(ByVal strLanguage As String, ByVal strKisyuCode As String, ByVal userState As Object)
            If (Me.GetMItemByLanguageOperationCompleted Is Nothing) Then
                Me.GetMItemByLanguageOperationCompleted = AddressOf Me.OnGetMItemByLanguageOperationCompleted
            End If
            Me.InvokeAsync("GetMItemByLanguage", New Object() {strLanguage, strKisyuCode}, Me.GetMItemByLanguageOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetMItemByLanguageOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetMItemByLanguageCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetMItemByLanguageCompleted(Me, New GetMItemByLanguageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/WcfKatahikiRenkei.Results")>  _
    Partial Public Class StandardNouki
        
        Private errMsgField As String
        
        Private fullKatabanField As String
        
        Private quantityField As Integer
        
        Private quantityFieldSpecified As Boolean
        
        Private quantityDispField As String
        
        Private stdDateField As Integer
        
        Private stdDateFieldSpecified As Boolean
        
        Private stdDateDispField As String
        
        Private zaikoFlgField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ErrMsg() As String
            Get
                Return Me.errMsgField
            End Get
            Set
                Me.errMsgField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property FullKataban() As String
            Get
                Return Me.fullKatabanField
            End Get
            Set
                Me.fullKatabanField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Quantity() As Integer
            Get
                Return Me.quantityField
            End Get
            Set
                Me.quantityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property QuantitySpecified() As Boolean
            Get
                Return Me.quantityFieldSpecified
            End Get
            Set
                Me.quantityFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property QuantityDisp() As String
            Get
                Return Me.quantityDispField
            End Get
            Set
                Me.quantityDispField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StdDate() As Integer
            Get
                Return Me.stdDateField
            End Get
            Set
                Me.stdDateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property StdDateSpecified() As Boolean
            Get
                Return Me.stdDateFieldSpecified
            End Get
            Set
                Me.stdDateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property StdDateDisp() As String
            Get
                Return Me.stdDateDispField
            End Get
            Set
                Me.stdDateDispField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ZaikoFlg() As String
            Get
                Return Me.zaikoFlgField
            End Get
            Set
                Me.zaikoFlgField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/WcfKatahikiRenkei.Results")>  _
    Partial Public Class MItemRecord
        
        Private itemCountField As String
        
        Private labelContentField As String
        
        Private zokuseiCodeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ItemCount() As String
            Get
                Return Me.itemCountField
            End Get
            Set
                Me.itemCountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property LabelContent() As String
            Get
                Return Me.labelContentField
            End Get
            Set
                Me.labelContentField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ZokuseiCode() As String
            Get
                Return Me.zokuseiCodeField
            End Get
            Set
                Me.zokuseiCodeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/WcfKatahikiRenkei.Results")>  _
    Partial Public Class MItem
        
        Private itemRecordsField() As MItemRecord
        
        Private specNoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property ItemRecords() As MItemRecord()
            Get
                Return Me.itemRecordsField
            End Get
            Set
                Me.itemRecordsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property SpecNo() As String
            Get
                Return Me.specNoField
            End Get
            Set
                Me.specNoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/WcfKatahikiRenkei.Results")>  _
    Partial Public Class SelectCatalog
        
        Private dispKosuField As String
        
        Private dispNokiField As String
        
        Private kaitoufukaKbnField As String
        
        Private katabanField As String
        
        Private kosuField As Integer
        
        Private kosuFieldSpecified As Boolean
        
        Private msgKbnField As String
        
        Private nokiField As Integer
        
        Private nokiFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property DispKosu() As String
            Get
                Return Me.dispKosuField
            End Get
            Set
                Me.dispKosuField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property DispNoki() As String
            Get
                Return Me.dispNokiField
            End Get
            Set
                Me.dispNokiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property KaitoufukaKbn() As String
            Get
                Return Me.kaitoufukaKbnField
            End Get
            Set
                Me.kaitoufukaKbnField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Kataban() As String
            Get
                Return Me.katabanField
            End Get
            Set
                Me.katabanField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Kosu() As Integer
            Get
                Return Me.kosuField
            End Get
            Set
                Me.kosuField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property KosuSpecified() As Boolean
            Get
                Return Me.kosuFieldSpecified
            End Get
            Set
                Me.kosuFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MsgKbn() As String
            Get
                Return Me.msgKbnField
            End Get
            Set
                Me.msgKbnField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Noki() As Integer
            Get
                Return Me.nokiField
            End Get
            Set
                Me.nokiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property NokiSpecified() As Boolean
            Get
                Return Me.nokiFieldSpecified
            End Get
            Set
                Me.nokiFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/WcfKatahikiRenkei.Results")>  _
    Partial Public Class QuantityUnit
        
        Private hasQuantityUnitField As Boolean
        
        Private hasQuantityUnitFieldSpecified As Boolean
        
        Private quantityUnitNameField As String
        
        Private quantityUnitNameDefaultField As String
        
        '''<remarks/>
        Public Property HasQuantityUnit() As Boolean
            Get
                Return Me.hasQuantityUnitField
            End Get
            Set
                Me.hasQuantityUnitField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property HasQuantityUnitSpecified() As Boolean
            Get
                Return Me.hasQuantityUnitFieldSpecified
            End Get
            Set
                Me.hasQuantityUnitFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property QuantityUnitName() As String
            Get
                Return Me.quantityUnitNameField
            End Get
            Set
                Me.quantityUnitNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property QuantityUnitNameDefault() As String
            Get
                Return Me.quantityUnitNameDefaultField
            End Get
            Set
                Me.quantityUnitNameDefaultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetStandardNokiCompletedEventHandler(ByVal sender As Object, ByVal e As GetStandardNokiCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetStandardNokiCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As StandardNouki
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),StandardNouki)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetElKubunCompletedEventHandler(ByVal sender As Object, ByVal e As GetElKubunCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetElKubunCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property GetElKubunResult() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property GetElKubunResultSpecified() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetElFlagCompletedEventHandler(ByVal sender As Object, ByVal e As GetElFlagCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetElFlagCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetQuantityUnitCompletedEventHandler(ByVal sender As Object, ByVal e As GetQuantityUnitCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetQuantityUnitCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As QuantityUnit
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),QuantityUnit)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetNetPriceCompletedEventHandler(ByVal sender As Object, ByVal e As GetNetPriceCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetNetPriceCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetSwitchFlgCompletedEventHandler(ByVal sender As Object, ByVal e As GetSwitchFlgCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetSwitchFlgCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property GetSwitchFlgResult() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property GetSwitchFlgResultSpecified() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetSelectCatalogCompletedEventHandler(ByVal sender As Object, ByVal e As GetSelectCatalogCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetSelectCatalogCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SelectCatalog
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SelectCatalog)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub IsGlcCompletedEventHandler(ByVal sender As Object, ByVal e As IsGlcCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class IsGlcCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property IsGlcResult() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property IsGlcResultSpecified() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetMItemByLanguageCompletedEventHandler(ByVal sender As Object, ByVal e As GetMItemByLanguageCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetMItemByLanguageCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MItem
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MItem)
            End Get
        End Property
    End Class
End Namespace
