'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace WSKatahikirenkei
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WSKatahikiRenkeiSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class WSKatahikiRenkei
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetStandardNokiOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WebKataban.My.MySettings.Default.WebKataban_WSKatahikirenkei_WSKatahikiRenkei
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetStandardNokiCompleted As GetStandardNokiCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStandardNoki", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetStandardNoki(ByVal strKata As String, ByVal strPlaceID As String) As StandardNoki
            Dim results() As Object = Me.Invoke("GetStandardNoki", New Object() {strKata, strPlaceID})
            Return CType(results(0),StandardNoki)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetStandardNokiAsync(ByVal strKata As String, ByVal strPlaceID As String)
            Me.GetStandardNokiAsync(strKata, strPlaceID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetStandardNokiAsync(ByVal strKata As String, ByVal strPlaceID As String, ByVal userState As Object)
            If (Me.GetStandardNokiOperationCompleted Is Nothing) Then
                Me.GetStandardNokiOperationCompleted = AddressOf Me.OnGetStandardNokiOperationCompleted
            End If
            Me.InvokeAsync("GetStandardNoki", New Object() {strKata, strPlaceID}, Me.GetStandardNokiOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetStandardNokiOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetStandardNokiCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetStandardNokiCompleted(Me, New GetStandardNokiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class StandardNoki
        
        Private fullKatabanField As String
        
        Private stdDateField As Integer
        
        Private stdDateDispField As String
        
        Private quantityField As Integer
        
        Private quantityDispField As String
        
        Private zaikoFlgField As String
        
        Private errMsgField As String
        
        '''<remarks/>
        Public Property fullKataban() As String
            Get
                Return Me.fullKatabanField
            End Get
            Set
                Me.fullKatabanField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property stdDate() As Integer
            Get
                Return Me.stdDateField
            End Get
            Set
                Me.stdDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property stdDateDisp() As String
            Get
                Return Me.stdDateDispField
            End Get
            Set
                Me.stdDateDispField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property quantity() As Integer
            Get
                Return Me.quantityField
            End Get
            Set
                Me.quantityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property quantityDisp() As String
            Get
                Return Me.quantityDispField
            End Get
            Set
                Me.quantityDispField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property zaikoFlg() As String
            Get
                Return Me.zaikoFlgField
            End Get
            Set
                Me.zaikoFlgField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrMsg() As String
            Get
                Return Me.errMsgField
            End Get
            Set
                Me.errMsgField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetStandardNokiCompletedEventHandler(ByVal sender As Object, ByVal e As GetStandardNokiCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetStandardNokiCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As StandardNoki
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),StandardNoki)
            End Get
        End Property
    End Class
End Namespace
